apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postfix.name" . }}
    helm.sh/chart: {{ include "postfix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  main.cf: |
    smtpd_banner = $myhostname ESMTP $mail_name
    maillog_file = /dev/stdout
    biff = no
    append_dot_mydomain = no
    readme_directory = no
    compatibility_level = 2
    smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
    myhostname = {{ .Values.postfix.relay_myhostname }}
    alias_maps = hash:/etc/aliases
    alias_database = hash:/etc/aliases
    mydestination = $myhostname, localhost.localdomain, , localhost
    {{ if .Values.postfix.relay_host }}
    relayhost = [{{ .Values.postfix.relay_host }}]:{{ .Values.postfix.relay_port }} 
    {{ else }}
    relayhost = 
    {{ end }}
    mynetworks = 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    mailbox_size_limit = 0
    recipient_delimiter = +
    inet_interfaces = all
    inet_protocols = all
    {{ if .Values.postfix.relay_auth }}
    smtp_sasl_auth_enable = yes
    smtp_sasl_password_maps = static:{{ .Values.postfix.relay_username }}:{{ .Values.postfix.relay_password }}
    smtp_sasl_security_options = noanonymous
    {{ end }}
    {{ if .Values.postfix.relay_tls }}
    smtp_tls_security_level = encrypt
    {{ end }}
    smtp_destination_rate_delay = 3600s
    smtp_destination_concurrency_limit = 2
    smtp_destination_recipient_limit = {{ .Values.postfix.limit_per_hour }}
  master.cf: |
    smtp      inet  n       -       n       -       -       smtpd
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       bounce
    trace     unix  -       -       n       -       0       bounce
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
            -o syslog_name=postfix/$service_name
    showq     unix  n       -       n       -       -       showq
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd